apiVersion: v1
kind: Service

metadata:
  name: smartims-backend-service
  namespace: smartims

spec:
  selector:
    app: smartims-backend

  ports:
  - port: 8081
    targetPort: 8081

  type: ClusterIP